apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: my-app-vue
  name: my-app-vue
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-app-vue
  template:
    metadata:
      labels:
        run: my-app-vue
    spec:
      containers:
      - image: gcr.io/airy-advantage-336608/my-app-vue:latest #Replace airy-advantage-336608 accordingly
        name: my-app-vue
        ports:
        - containerPort: 8080
